apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  namespace: gleam
spec:
  template:
    spec:
      containers:
        - name: master
          image: local/gleam
          imagePullPolicy: Never